# Generated by Django 4.2.20 on 2025-05-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_conversation_is_cto_chat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="is_cto_chat",
        ),
        migrations.AddField(
            model_name="conversation",
            name="chat_type",
            field=models.CharField(
                choices=[("cto", "CTO Chat"), ("dev", "Developer Chat")],
                default="cto",
                max_length=10,
            ),
        ),
    ]
